# Generated by Django 4.1 on 2022-09-03 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="first_name",
            field=models.CharField(max_length=42, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="last_name",
            field=models.CharField(max_length=42, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="phonenumber",
            field=models.IntegerField(verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user id",
            ),
        ),
    ]
