# Generated by Django 4.1 on 2022-09-04 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_phone_first_name_alter_phone_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="phonenumber",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="invalid phone number!",
                        regex="/^(?:98|\\+98|0098|0)?9[0-9]{9}$/",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
