# Generated by Django 4.1 on 2022-09-04 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0005_alter_phone_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user id",
            ),
        ),
    ]
