# Generated by Django 4.1 on 2022-09-05 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_phone_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="phonenumber",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid phone number!",
                        regex="(0|\\+98)?([ ]|-|[()]){0,2}9[1|2|3|4|5|6|7|8|9]([ ]|-|[()]){0,2}(?:[0-9]([ ]|-|[()]){0,2}){8}",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
